title: Mitochondrial Content
type: object
properties:
  enabled:
    type: boolean
  auto:
    type: boolean
  filterSettings:
    type: object
    required:
      - method
      - methodSettings
    properties:
      method:
        type: string
        minLength: 1
      methodSettings:
        type: object
        properties:
          absoluteThreshold:
            type: object
            properties:
              maxFraction:
                type: number
              binStep:
                type: number
additionalProperties:
  type: object
  properties:
    filterSettings:
      type: object
      required:
        - method
        - methodSettings
      properties:
        method:
          type: string
          minLength: 1
        methodSettings:
          type: object
          properties:
            absoluteThreshold:
              type: object
              properties:
                maxFraction:
                  type: number
                binStep:
                  type: number         
required:
  - filterSettings
description: Processing config body for Mitochondrial Content filter.
